import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import FirebaseAuthProvider from "@/components/providers/auth-providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col items-center h-screen w-screen bg-slate-800 pt-40">
          <FirebaseAuthProvider>
            <Navbar />
            {children}
          </FirebaseAuthProvider>
        </main>
      </body>
    </html>
  );
}
